
import { IPDEntry, InstructionEntry } from "./types";

export const ADMITTED_PATIENTS_DATA: IPDEntry[] = [
    {
        id: "1",
        bedNo: "B-01",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        ipdId: "IPD ID-1000",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy", // Sic: matching screenshot typo if any, or just Cardiology
        admissionDate: "20-11-2025",
        time: "09:00 Am",
        location: "12A - Ward 1 - B101",
        bill: "120AED",
        status: "Critical",
    },
    {
        id: "2",
        bedNo: "B-01",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        ipdId: "IPD ID-1000",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        admissionDate: "20-11-2025",
        time: "09:00 Am",
        location: "12A - Ward 1 - B101",
        bill: "120AED",
        status: "Critical",
    },
    {
        id: "3",
        bedNo: "B-01",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        ipdId: "IPD ID-1000",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        admissionDate: "20-11-2025",
        time: "09:00 Am",
        location: "12A - Ward 1 - B101",
        bill: "120AED",
        status: "Critical",
    },
    {
        id: "4",
        bedNo: "B-01",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        ipdId: "IPD ID-1000",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        admissionDate: "20-11-2025",
        time: "09:00 Am",
        location: "12A - Ward 1 - B101",
        bill: "120AED",
        status: "Critical",
    },
    {
        id: "5",
        bedNo: "B-01",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        ipdId: "IPD ID-1000",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        admissionDate: "20-11-2025",
        time: "09:00 Am",
        location: "12A - Ward 1 - B101",
        bill: "120AED",
        status: "Stable",
    },
    {
        id: "6",
        bedNo: "B-01",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        ipdId: "IPD ID-1000",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        admissionDate: "20-11-2025",
        time: "09:00 Am",
        location: "12A - Ward 1 - B101",
        bill: "120AED",
        status: "Stable",
    },
    {
        id: "7",
        bedNo: "B-01",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        ipdId: "IPD ID-1000",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        admissionDate: "20-11-2025",
        time: "09:00 Am",
        location: "12A - Ward 1 - B101",
        bill: "120AED",
        status: "Stable",
    },
    {
        id: "8",
        bedNo: "B-01",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        ipdId: "IPD ID-1000",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        admissionDate: "20-11-2025",
        time: "09:00 Am",
        location: "12A - Ward 1 - B101",
        bill: "120AED",
        status: "Stable",
    },
    {
        id: "9",
        bedNo: "B-01",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        ipdId: "IPD ID-1000",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardiology",
        admissionDate: "20-11-2025",
        time: "09:00 Am",
        location: "12A - Ward 1 - B101",
        bill: "120AED",
        status: "Stable",
    },
];

export const DISCHARGED_PATIENTS_DATA: IPDEntry[] = [
    {
        id: "d1",
        bedNo: "-",
        patientName: "Ganguli Rathod",
        mrn: "00324891",
        ipdId: "VID-34522",
        patientImg: "", // Empty to show AvatarFallback (Letter G)
        doctorName: "Dr. Kiran Madha",
        specialty: "Cardiology",
        admissionDate: "2024-03-10",
        time: "10:30 AM",
        location: "-",
        bill: "₹ 45,000",
        status: "Discharged",
        dischargeDate: "2024-03-15",

        // Follow-up Mock Data
        followUpDate: "2025-09-27 19:30",
        visitType: "OPD",
        reason: "Review blood reports",
        appointmentType: "In-person",
        createdOn: "27-09-2025"
    },
    {
        id: "d2",
        bedNo: "-",
        patientName: "Ramesh Pawar",
        mrn: "00324892",
        ipdId: "VID-34523",
        patientImg: "", // Empty to show AvatarFallback
        doctorName: "Dr. Sarah Smith",
        specialty: "Orthopedics",
        admissionDate: "2024-03-12",
        time: "02:15 PM",
        location: "-",
        bill: "₹ 32,000",
        status: "Discharged",
        dischargeDate: "2024-03-16",

        // Follow-up Mock Data
        followUpDate: "2025-09-28 10:00",
        visitType: "OPD",
        reason: "Post-surgery checkup",
        appointmentType: "In-person",
        createdOn: "28-09-2025"
    },
];


// Reusing mock data logic from OPD for instructions
export const NURSE_TASKS_DATA: InstructionEntry[] = [
    {
        id: "1",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "IPD ID-1000",
        nurseName: "Dr.Kiran Madha",
        nurseRole: "OT Nurse",
        orderType: "Wound Dressing",
        description: "Dressing change on left leg wound",
        frequency: "Daily",
        dateTime: "2025-09-27 19:30",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        priority: "Urgent",
        status: "Pending",
    },
    // ... more items can be added
    {
        id: "2",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "IPD ID-1000",
        nurseName: "Dr.Kiran Madha",
        nurseRole: "OT Nurse",
        orderType: "Wound Dressing",
        description: "Dressing change on left leg wound",
        frequency: "Daily",
        dateTime: "2025-09-27 19:30",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        priority: "Urgent",
        status: "Pending",
    },
    {
        id: "3",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "IPD ID-1000",
        nurseName: "Dr.Kiran Madha",
        nurseRole: "OT Nurse",
        orderType: "Wound Dressing",
        description: "Dressing change on left leg wound",
        frequency: "Daily",
        dateTime: "2025-09-27 19:30",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        priority: "Urgent",
        status: "Pending",
    },
];

export const LAB_ORDERS_DATA: InstructionEntry[] = [
    {
        id: "1",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "LID-324135",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        orderedDate: "2025-09-27 19:30",
        testName: "Complete Blood Count (CBC)",
        category: "Biochemistry",
        urgency: "Routine",
        priority: "Normal",
        status: "Completed",
    },
    {
        id: "2",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "LID-324135",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        orderedDate: "2025-09-27 19:30",
        testName: "Complete Blood Count (CBC)",
        category: "Biochemistry",
        urgency: "Routine",
        priority: "Normal",
        status: "Completed",
    },
    {
        id: "3",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "LID-324135",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        orderedDate: "2025-09-27 19:30",
        testName: "Complete Blood Count (CBC)",
        category: "Biochemistry",
        urgency: "Routine",
        priority: "Normal",
        status: "Completed",
    },
];
