const ADMINISTRATION_BASE = '/administration';

export const ROUTES = {
    ADMINISTRATION: ADMINISTRATION_BASE,
    ADMINISTRATION_CHARGES: `${ADMINISTRATION_BASE}/charges`,
    ADMINISTRATION_CHARGES_ADD: `${ADMINISTRATION_BASE}/charges/add`,
    ADMINISTRATION_DEPARTMENT: `${ADMINISTRATION_BASE}/department`,
    ADMINISTRATION_INSURANCE: `${ADMINISTRATION_BASE}/insurance`,
    ADMINISTRATION_INSURANCE_ADD: `${ADMINISTRATION_BASE}/insurance/add`,
    ADMINISTRATION_OPERATION: `${ADMINISTRATION_BASE}/operation`,
    ADMINISTRATION_OPERATION_THEATRES: `${ADMINISTRATION_BASE}/operation-theatres`,
    ADMINISTRATION_ROLES: `${ADMINISTRATION_BASE}/roles`,
    ADMINISTRATION_ROLES_PERMISSIONS: `${ADMINISTRATION_BASE}/roles/permissions`,
    ADMINISTRATION_UNITS_WARDS_BEDS: `${ADMINISTRATION_BASE}/units-wards-beds`,
    ADMINISTRATION_USER: `${ADMINISTRATION_BASE}/user`,

};