import { OPDEntry, InstructionEntry } from "./types";

export const MOCK_OPD_DATA: OPDEntry[] = [
    {
        id: "1",
        tokenNo: "T-101",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "APP-283947",
        patientImg: "", // fallback to initial
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        date: "20-11-2025",
        time: "09:00 Am",
        bookingType: "New Consultation",
        priorityType: "VIP",
        status: "In Consultation",
    },
    {
        id: "2",
        tokenNo: "T-101",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "APP-283947",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        date: "20-11-2025",
        time: "09:00 Am",
        bookingType: "New Consultation",
        priorityType: "VIP",
        status: "Called",
    },
    {
        id: "3",
        tokenNo: "T-101",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "APP-283947",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        date: "20-11-2025",
        time: "09:00 Am",
        bookingType: "New Consultation",
        priorityType: "VIP",
        status: "In Consultation",
    },
    {
        id: "4",
        tokenNo: "T-101",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "APP-283947",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        date: "20-11-2025",
        time: "09:00 Am",
        bookingType: "New Consultation",
        priorityType: "VIP",
        status: "Booked",
    },
    {
        id: "5",
        tokenNo: "T-101",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "APP-283947",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        date: "20-11-2025",
        time: "09:00 Am",
        bookingType: "New Consultation",
        priorityType: "VIP",
        status: "Booked",
    },
    {
        id: "6",
        tokenNo: "T-101",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "APP-283947",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        date: "20-11-2025",
        time: "09:00 Am",
        bookingType: "New Consultation",
        priorityType: "VIP",
        status: "Waiting",
    },
];

export const COMPLETED_OPD_DATA: OPDEntry[] = [
    {
        id: "10",
        tokenNo: "T-99",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "VID-34522",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        date: "2025-09-27", // Follow-Up Date
        time: "19:30",
        bookingType: "Follow Up",
        priorityType: "Normal",
        status: "Pending",
        reason: "Review blood reports",
        type: "In-person",
        createdOn: "27-09-2025",
    },
    {
        id: "11",
        tokenNo: "T-100",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "VID-34522",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        date: "2025-09-27",
        time: "19:30",
        bookingType: "Follow Up",
        priorityType: "Normal",
        status: "Completed",
        reason: "Review blood reports",
        type: "In-person",
        createdOn: "27-09-2025",
    },
    {
        id: "12",
        tokenNo: "T-101",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "VID-34522",
        patientImg: "",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        date: "2025-09-27",
        time: "19:30",
        bookingType: "Follow Up",
        priorityType: "Normal",
        status: "Missed",
        reason: "Review blood reports",
        type: "In-person",
        createdOn: "27-09-2025",
    },
];

export const NURSE_TASKS_DATA: InstructionEntry[] = [
    {
        id: "1",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "Visit ID-1000",
        nurseName: "Dr.Kiran Madha",
        nurseRole: "OT Nurse",
        orderType: "Wound Dressing",
        description: "Dressing change on left leg wound",
        frequency: "Daily",
        dateTime: "2025-09-27 19:30",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        priority: "Urgent",
        status: "Pending",
    },
    {
        id: "2",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "Visit ID-1000",
        nurseName: "Dr.Kiran Madha",
        nurseRole: "OT Nurse",
        orderType: "Wound Dressing",
        description: "Dressing change on left leg wound",
        frequency: "Daily",
        dateTime: "2025-09-27 19:30",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        priority: "Urgent",
        status: "Pending",
    },
    {
        id: "3",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "Visit ID-1000",
        nurseName: "Dr.Kiran Madha",
        nurseRole: "OT Nurse",
        orderType: "Wound Dressing",
        description: "Dressing change on left leg wound",
        frequency: "Daily",
        dateTime: "2025-09-27 19:30",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        priority: "Urgent",
        status: "Pending",
    },
];

export const LAB_ORDERS_DATA: InstructionEntry[] = [
    {
        id: "1",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "LID-324135",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        orderedDate: "2025-09-27 19:30",
        testName: "Complete Blood Count (CBC)",
        category: "Biochemistry",
        urgency: "Routine",
        priority: "Normal", // Mapped for UI color if needed
        status: "Completed",
    },
    {
        id: "2",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "LID-324135",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        orderedDate: "2025-09-27 19:30",
        testName: "Complete Blood Count (CBC)",
        category: "Biochemistry",
        urgency: "Routine",
        priority: "Normal",
        status: "Completed",
    },
    {
        id: "3",
        patientName: "Ganguli Rathod",
        mrn: "MRN 00324891",
        visitId: "LID-324135",
        doctorName: "Dr.Kiran Madha",
        specialty: "Cardialgy",
        orderedDate: "2025-09-27 19:30",
        testName: "Complete Blood Count (CBC)",
        category: "Biochemistry",
        urgency: "Routine",
        priority: "Normal",
        status: "Completed",
    },
];
