// _component/api.ts

import { AppointmentItem } from "./types/appointment"

export async function getAppointments(): Promise<AppointmentItem[]> {
  return new Promise<AppointmentItem[]>((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: "1",
          name: "Fatima Al-Sabah",
          mrn: "2501",
          avatar: "/avatar.png",
          vip: false,
          type: "emergency",
          room: "T-101",
          time: "09:00",
          status: "in-progress",
          note: "Stomach discomfort for 2 weeks",
          details: "Stomach discomfort for 2 weeks",
          insurance: "Kuwait Insurance",
          insuranceName: "Kuwait Insurance",
          age: "55Y / Male",
          phone: "283041234567",
        },
        {
          id: "2",
          name: "Fatima Al-Sabah",
          mrn: "2501",
          avatar: "/avatar 1.png",
          vip: false,
          type: "emergency",
          room: "T-101",
          time: "09:00",
          status: "in-progress",
          note: "Stomach discomfort for 2 weeks",
          details: "Stomach discomfort for 2 weeks",
          insurance: "Kuwait Insurance",
          insuranceName: "Kuwait Insurance",
          age: "55Y / Male",
          phone: "283041234567",
        },
        {
          id: "3",
          name: "Fatima Al-Sabah",
          mrn: "2501",
          avatar: "/avatar 1.png",
          vip: true,
          type: "vip",
          room: "T-101",
          time: "09:00",
          status: "waiting",
          note: "Follow up",
          details: "Follow up",
          insurance: "Gulf Insurance",
          insuranceName: "Gulf Insurance",
          age: "55Y / Male",
          phone: "283041234567",
        },
        {
          id: "4",
          name: "Fatima Al-Sabah",
          mrn: "2501",
          avatar: "/avatar 1.png",
          vip: true,
          type: "vip",
          room: "T-101",
          time: "09:00",
          status: "waiting",
          note: "Follow up",
          details: "Follow up",
          insurance: "Gulf Insurance",
          insuranceName: "Gulf Insurance",
          age: "55Y / Male",
          phone: "283041234567",
        },
        {
          id: "5",
          name: "Fatima Al-Sabah",
          mrn: "2501",
          avatar: "/avatar 1.png",
          vip: false,
          type: "general",
          room: "T-101",
          time: "09:00",
          status: "waiting",
          note: "",
          details: "",
          insurance: "",
          insuranceName: "",
          age: "55Y / Male",
          phone: "283041234567",
        },
        {
          id: "6",
          name: "Fatima Al-Sabah",
          mrn: "2501",
          avatar: "/avatar 1.png",
          vip: false,
          type: "general",
          room: "T-101",
          time: "09:00",
          status: "waiting",
          note: "",
          details: "",
          insurance: "",
          insuranceName: "",
          age: "55Y / Male",
          phone: "283041234567",
        },
      ])
    }, 900)
  })
}
